apiVersion: v1
kind: Service
metadata:
    name: "nastasia2-455f"
    labels:
        app: "nastasia2-455f"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "nastasia2-455f"